modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "fpsguard"
version = "1.0.0"
displayName = "FPS Guard"
authors = "Emir"
description = '''
FPS ve RAM koruyucu. FPS hedefin altına düşünce uzak entity ve render mesafesini kademeli kısar,
FPS düzelince geri açar. RAM dolunca güvenli şekilde bellek temizler. Pencere arka plandayken FPS'i düşürür.
'''

[[dependencies.fpsguard]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.fpsguard]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1]"
ordering = "NONE"
side = "CLIENT"
